# Issue 关闭 时自动放置到工作台 “已完成” 列，并删除“待回应”、“待处理”标签

name: 【Closed】Label and move to project on issue closed
on:
  issues:
    types: [closed]

jobs:
  move-to-done:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: "工作台"
          column: "已完成"
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}

  remove-labels:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Remove labels
        uses: andymckay/labeler@master
        with:
          remove-labels: "待处理, 待回应, 处理中"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
